/* ============================================================
   Alltags-Deutsch — words-data.js
   Vocabulary lists for the Words page (words.html), one array
   per CEFR level. WORDS holds every entry with its level and
   its alphabet group ("letter"), so words.js can render them
   as clickable, speakable tickets grouped A–Z, and filter them
   by level or by a search query.

   Source: Goethe-Institut "Start Deutsch 1" (A1) Wortliste.
   To add A2/B1/B2 later: push more { level, letter, de, en }
   objects into WORDS with the matching level id.
   ============================================================ */

const WORD_LEVELS = [
  { id: "A1", label: "Beginner", sublabel: "A1" },
  { id: "A2", label: "Beginner", sublabel: "A2" },
  { id: "B1", label: "Intermediate", sublabel: "B1" },
  { id: "B2", label: "Intermediate", sublabel: "B2" }
];

const WORDS = [
  { level: "A1", letter: "A", de: "ab", en: "from, starting" },
  { level: "A1", letter: "A", de: "aber", en: "but" },
  { level: "A1", letter: "A", de: "abfahren", en: "to depart" },
  { level: "A1", letter: "A", de: "die Abfahrt", en: "departure" },
  { level: "A1", letter: "A", de: "abgeben", en: "to hand in/over" },
  { level: "A1", letter: "A", de: "abholen", en: "to pick up" },
  { level: "A1", letter: "A", de: "der Absender", en: "sender" },
  { level: "A1", letter: "A", de: "Achtung", en: "attention, caution" },
  { level: "A1", letter: "A", de: "die Adresse, -n", en: "address" },
  { level: "A1", letter: "A", de: "all-", en: "all" },
  { level: "A1", letter: "A", de: "allein", en: "alone" },
  { level: "A1", letter: "A", de: "also", en: "so, therefore" },
  { level: "A1", letter: "A", de: "alt", en: "old" },
  { level: "A1", letter: "A", de: "das Alter", en: "age" },
  { level: "A1", letter: "A", de: "an", en: "at, on" },
  { level: "A1", letter: "A", de: "anbieten", en: "to offer" },
  { level: "A1", letter: "A", de: "das Angebot, -e", en: "offer, special" },
  { level: "A1", letter: "A", de: "ander-", en: "other" },
  { level: "A1", letter: "A", de: "anfangen", en: "to begin" },
  { level: "A1", letter: "A", de: "der Anfang", en: "beginning" },
  { level: "A1", letter: "A", de: "anklicken", en: "to click on" },
  { level: "A1", letter: "A", de: "ankommen", en: "to arrive" },
  { level: "A1", letter: "A", de: "die Ankunft", en: "arrival" },
  { level: "A1", letter: "A", de: "ankreuzen", en: "to tick/check a box" },
  { level: "A1", letter: "A", de: "anmachen", en: "to switch on" },
  { level: "A1", letter: "A", de: "(sich) anmelden", en: "to register (oneself)" },
  { level: "A1", letter: "A", de: "die Anmeldung", en: "registration" },
  { level: "A1", letter: "A", de: "die Anrede", en: "salutation, form of address" },
  { level: "A1", letter: "A", de: "anrufen", en: "to call (phone)" },
  { level: "A1", letter: "A", de: "der Anruf, -e", en: "phone call" },
  { level: "A1", letter: "A", de: "der Anrufbeantworter", en: "answering machine" },
  { level: "A1", letter: "A", de: "die Ansage, -n", en: "announcement" },
  { level: "A1", letter: "A", de: "der Anschluss", en: "connection" },
  { level: "A1", letter: "A", de: "an sein", en: "to be on (light, device)" },
  { level: "A1", letter: "A", de: "antworten", en: "to answer" },
  { level: "A1", letter: "A", de: "die Antwort, -en", en: "answer" },
  { level: "A1", letter: "A", de: "die Anzeige, -n", en: "advertisement, notice" },
  { level: "A1", letter: "A", de: "(sich) anziehen", en: "to get dressed" },
  { level: "A1", letter: "A", de: "das Apartment, -s", en: "apartment" },
  { level: "A1", letter: "A", de: "der Apfel, -Ä", en: "apple" },
  { level: "A1", letter: "A", de: "der Appetit", en: "appetite" },
  { level: "A1", letter: "A", de: "arbeiten", en: "to work" },
  { level: "A1", letter: "A", de: "die Arbeit, -en", en: "work" },
  { level: "A1", letter: "A", de: "arbeitslos", en: "unemployed" },
  { level: "A1", letter: "A", de: "der Arbeitsplatz", en: "workplace" },
  { level: "A1", letter: "A", de: "der Arm, -e", en: "arm" },
  { level: "A1", letter: "A", de: "der Arzt, -Ä, e", en: "doctor" },
  { level: "A1", letter: "A", de: "auch", en: "also, too" },
  { level: "A1", letter: "A", de: "auf", en: "on, open" },
  { level: "A1", letter: "A", de: "die Aufgabe, -n", en: "task" },
  { level: "A1", letter: "A", de: "aufhören", en: "to stop, end" },
  { level: "A1", letter: "A", de: "auf sein", en: "to be open" },
  { level: "A1", letter: "A", de: "aufstehen", en: "to get up" },
  { level: "A1", letter: "A", de: "der Aufzug, -ü, e", en: "elevator" },
  { level: "A1", letter: "A", de: "das Auge, -n", en: "eye" },
  { level: "A1", letter: "A", de: "aus", en: "from, out of" },
  { level: "A1", letter: "A", de: "der Ausflug", en: "excursion, trip" },
  { level: "A1", letter: "A", de: "ausfüllen", en: "to fill out" },
  { level: "A1", letter: "A", de: "der Ausgang", en: "exit" },
  { level: "A1", letter: "A", de: "die Auskunft, -ü, e", en: "information" },
  { level: "A1", letter: "A", de: "das Ausland", en: "abroad" },
  { level: "A1", letter: "A", de: "der Ausländer, -", en: "foreigner" },
  { level: "A1", letter: "A", de: "ausländisch", en: "foreign" },
  { level: "A1", letter: "A", de: "ausmachen", en: "to switch off" },
  { level: "A1", letter: "A", de: "die Aussage, -n", en: "statement" },
  { level: "A1", letter: "A", de: "aussehen", en: "to look, appear" },
  { level: "A1", letter: "A", de: "aus sein", en: "to be off/finished" },
  { level: "A1", letter: "A", de: "aussteigen", en: "to get off/out" },
  { level: "A1", letter: "A", de: "der Ausweis", en: "ID card" },
  { level: "A1", letter: "A", de: "(sich) ausziehen", en: "to undress" },
  { level: "A1", letter: "A", de: "das Auto, -s", en: "car" },
  { level: "A1", letter: "A", de: "die Autobahn, -en", en: "highway" },
  { level: "A1", letter: "A", de: "der Automat", en: "vending machine" },
  { level: "A1", letter: "A", de: "automatisch", en: "automatic" },
  { level: "A1", letter: "B", de: "das Baby, -s", en: "baby" },
  { level: "A1", letter: "B", de: "die Bäckerei", en: "bakery" },
  { level: "A1", letter: "B", de: "das Bad", en: "bathroom, bath" },
  { level: "A1", letter: "B", de: "baden", en: "to bathe" },
  { level: "A1", letter: "B", de: "die Bahn", en: "train, railway" },
  { level: "A1", letter: "B", de: "der Bahnhof", en: "train station" },
  { level: "A1", letter: "B", de: "der Bahnsteig", en: "platform" },
  { level: "A1", letter: "B", de: "bald", en: "soon" },
  { level: "A1", letter: "B", de: "der Balkon", en: "balcony" },
  { level: "A1", letter: "B", de: "die Banane, -n", en: "banana" },
  { level: "A1", letter: "B", de: "die Bank", en: "bank; bench" },
  { level: "A1", letter: "B", de: "bar", en: "cash" },
  { level: "A1", letter: "B", de: "der Bauch", en: "stomach" },
  { level: "A1", letter: "B", de: "der Baum, -ä, e", en: "tree" },
  { level: "A1", letter: "B", de: "der Beamte, -n", en: "official, clerk" },
  { level: "A1", letter: "B", de: "bedeuten", en: "to mean" },
  { level: "A1", letter: "B", de: "beginnen", en: "to begin" },
  { level: "A1", letter: "B", de: "bei", en: "at, near, with" },
  { level: "A1", letter: "B", de: "beide", en: "both" },
  { level: "A1", letter: "B", de: "das Bein, -e", en: "leg" },
  { level: "A1", letter: "B", de: "das Beispiel, -e", en: "example" },
  { level: "A1", letter: "Z", de: "zum Beispiel/z. B.", en: "for example" },
  { level: "A1", letter: "B", de: "bekannt", en: "known, famous" },
  { level: "A1", letter: "D", de: "der/die Bekannte, -n", en: "acquaintance" },
  { level: "A1", letter: "B", de: "bekommen", en: "to receive, get" },
  { level: "A1", letter: "B", de: "benutzen", en: "to use" },
  { level: "A1", letter: "B", de: "der Beruf, -e", en: "profession" },
  { level: "A1", letter: "B", de: "besetzt", en: "occupied, busy" },
  { level: "A1", letter: "B", de: "besichtigen", en: "to visit, sightsee" },
  { level: "A1", letter: "B", de: "besser", en: "better" },
  { level: "A1", letter: "B", de: "best-", en: "best" },
  { level: "A1", letter: "B", de: "bestellen", en: "to order" },
  { level: "A1", letter: "B", de: "besuchen", en: "to visit" },
  { level: "A1", letter: "B", de: "das Bett, -en", en: "bed" },
  { level: "A1", letter: "B", de: "bezahlen", en: "to pay" },
  { level: "A1", letter: "B", de: "das Bier", en: "beer" },
  { level: "A1", letter: "B", de: "das Bild, -er", en: "picture" },
  { level: "A1", letter: "B", de: "billig", en: "cheap" },
  { level: "A1", letter: "B", de: "die Birne, -n", en: "pear" },
  { level: "A1", letter: "B", de: "bis", en: "until" },
  { level: "A1", letter: "B", de: "bisschen", en: "a little bit" },
  { level: "A1", letter: "B", de: "bitte", en: "please" },
  { level: "A1", letter: "B", de: "die Bitte, -n", en: "request" },
  { level: "A1", letter: "B", de: "bitten", en: "to ask, request" },
  { level: "A1", letter: "B", de: "bitter", en: "bitter" },
  { level: "A1", letter: "B", de: "bleiben", en: "to stay" },
  { level: "A1", letter: "B", de: "der Bleistift, -e", en: "pencil" },
  { level: "A1", letter: "B", de: "der Blick", en: "view, glance" },
  { level: "A1", letter: "B", de: "die Blume, -n", en: "flower" },
  { level: "A1", letter: "B", de: "der Bogen", en: "sheet (of paper), form" },
  { level: "A1", letter: "B", de: "böse", en: "angry, mad" },
  { level: "A1", letter: "B", de: "brauchen", en: "to need" },
  { level: "A1", letter: "B", de: "breit", en: "wide" },
  { level: "A1", letter: "B", de: "der Brief, -e", en: "letter" },
  { level: "A1", letter: "B", de: "die Briefmarke, -n", en: "stamp" },
  { level: "A1", letter: "B", de: "bringen", en: "to bring" },
  { level: "A1", letter: "B", de: "das Brot, -e", en: "bread" },
  { level: "A1", letter: "B", de: "das Brötchen, -", en: "bread roll" },
  { level: "A1", letter: "B", de: "der Bruder, -ü", en: "brother" },
  { level: "A1", letter: "B", de: "das Buch, -ü, er", en: "book" },
  { level: "A1", letter: "B", de: "der Buchstabe, -n", en: "letter (of alphabet)" },
  { level: "A1", letter: "B", de: "buchstabieren", en: "to spell" },
  { level: "A1", letter: "B", de: "der Bus, -se", en: "bus" },
  { level: "A1", letter: "B", de: "die Butter", en: "butter" },
  { level: "A1", letter: "C", de: "das Café, -s", en: "café" },
  { level: "A1", letter: "C", de: "die CD, -s", en: "CD" },
  { level: "A1", letter: "C", de: "der Chef", en: "boss" },
  { level: "A1", letter: "C", de: "circa/ca.", en: "approximately" },
  { level: "A1", letter: "C", de: "der Computer, -", en: "computer" },
  { level: "A1", letter: "D", de: "da", en: "there; since" },
  { level: "A1", letter: "D", de: "die Dame, -n", en: "lady" },
  { level: "A1", letter: "D", de: "daneben", en: "next to it" },
  { level: "A1", letter: "D", de: "danken", en: "to thank" },
  { level: "A1", letter: "D", de: "der Dank", en: "thanks" },
  { level: "A1", letter: "D", de: "danke", en: "thank you" },
  { level: "A1", letter: "D", de: "dann", en: "then" },
  { level: "A1", letter: "D", de: "das Datum", en: "date" },
  { level: "A1", letter: "D", de: "dauern", en: "to last, take (time)" },
  { level: "A1", letter: "D", de: "dein-", en: "your (informal)" },
  { level: "A1", letter: "D", de: "denn", en: "because" },
  { level: "A1", letter: "D", de: "der, die, das", en: "the" },
  { level: "A1", letter: "D", de: "dich", en: "you (accusative)" },
  { level: "A1", letter: "D", de: "dies-", en: "this" },
  { level: "A1", letter: "D", de: "dir", en: "you (dative)" },
  { level: "A1", letter: "D", de: "die Disco", en: "disco, club" },
  { level: "A1", letter: "D", de: "der Doktor", en: "doctor" },
  { level: "A1", letter: "D", de: "das Doppelzimmer", en: "double room" },
  { level: "A1", letter: "D", de: "das Dorf, -ö, er", en: "village" },
  { level: "A1", letter: "D", de: "dort, -her, -hin", en: "there, from there, to there" },
  { level: "A1", letter: "D", de: "draußen", en: "outside" },
  { level: "A1", letter: "D", de: "drucken", en: "to print" },
  { level: "A1", letter: "D", de: "der Drucker, -", en: "printer" },
  { level: "A1", letter: "D", de: "drücken", en: "to press, push" },
  { level: "A1", letter: "D", de: "durch", en: "through" },
  { level: "A1", letter: "D", de: "die Durchsage, -n", en: "announcement" },
  { level: "A1", letter: "D", de: "dürfen", en: "to be allowed to, may" },
  { level: "A1", letter: "D", de: "der Durst", en: "thirst" },
  { level: "A1", letter: "D", de: "(sich) duschen", en: "to shower" },
  { level: "A1", letter: "D", de: "die Dusche", en: "shower" },
  { level: "A1", letter: "E", de: "die Ecke, -n", en: "corner" },
  { level: "A1", letter: "E", de: "die Ehefrau, -en", en: "wife" },
  { level: "A1", letter: "E", de: "der Ehemann, ä, er", en: "husband" },
  { level: "A1", letter: "E", de: "das Ei, -er", en: "egg" },
  { level: "A1", letter: "E", de: "eilig", en: "urgent, in a hurry" },
  { level: "A1", letter: "E", de: "ein-", en: "a, an, one" },
  { level: "A1", letter: "E", de: "einfach", en: "simple; one-way" },
  { level: "A1", letter: "E", de: "der Eingang", en: "entrance" },
  { level: "A1", letter: "E", de: "einkaufen", en: "to shop" },
  { level: "A1", letter: "E", de: "einladen", en: "to invite" },
  { level: "A1", letter: "E", de: "die Einladung", en: "invitation" },
  { level: "A1", letter: "E", de: "einmal", en: "once" },
  { level: "A1", letter: "E", de: "einsteigen", en: "to board, get in" },
  { level: "A1", letter: "E", de: "der Eintritt", en: "admission" },
  { level: "A1", letter: "E", de: "das Einzelzimmer", en: "single room" },
  { level: "A1", letter: "E", de: "die Eltern (pl.)", en: "parents" },
  { level: "A1", letter: "E", de: "die E-Mail, -s", en: "email" },
  { level: "A1", letter: "E", de: "der Empfänger, -", en: "recipient" },
  { level: "A1", letter: "E", de: "empfehlen", en: "to recommend" },
  { level: "A1", letter: "E", de: "enden", en: "to end" },
  { level: "A1", letter: "E", de: "das Ende", en: "end" },
  { level: "A1", letter: "E", de: "entschuldigen", en: "to excuse, apologize" },
  { level: "A1", letter: "E", de: "die Entschuldigung", en: "excuse, apology" },
  { level: "A1", letter: "E", de: "er", en: "he" },
  { level: "A1", letter: "E", de: "das Ergebnis, -se", en: "result" },
  { level: "A1", letter: "E", de: "erklären", en: "to explain" },
  { level: "A1", letter: "E", de: "erlauben", en: "to allow" },
  { level: "A1", letter: "E", de: "der Erwachsene, -n", en: "adult" },
  { level: "A1", letter: "E", de: "erzählen", en: "to tell, narrate" },
  { level: "A1", letter: "E", de: "es", en: "it" },
  { level: "A1", letter: "E", de: "essen", en: "to eat" },
  { level: "A1", letter: "E", de: "das Essen", en: "food, meal" },
  { level: "A1", letter: "E", de: "euer", en: "your (plural, informal)" },
  { level: "A1", letter: "F", de: "fahren", en: "to drive, go (by vehicle)" },
  { level: "A1", letter: "F", de: "der Fahrer", en: "driver" },
  { level: "A1", letter: "F", de: "die Fahrkarte, -n", en: "ticket (travel)" },
  { level: "A1", letter: "F", de: "das Fahrrad, -ä, er", en: "bicycle" },
  { level: "A1", letter: "F", de: "falsch", en: "wrong, false" },
  { level: "A1", letter: "F", de: "die Familie, -n", en: "family" },
  { level: "A1", letter: "F", de: "der Familienname", en: "surname" },
  { level: "A1", letter: "F", de: "der Familienstand", en: "marital status" },
  { level: "A1", letter: "F", de: "die Farbe, -n", en: "color" },
  { level: "A1", letter: "F", de: "das Fax, -e", en: "fax" },
  { level: "A1", letter: "F", de: "Feier-", en: "celebration-" },
  { level: "A1", letter: "F", de: "feiern", en: "to celebrate" },
  { level: "A1", letter: "F", de: "fehlen", en: "to be missing/absent" },
  { level: "A1", letter: "F", de: "der Fehler, -", en: "mistake" },
  { level: "A1", letter: "F", de: "fernsehen", en: "to watch TV" },
  { level: "A1", letter: "F", de: "fertig", en: "ready, finished" },
  { level: "A1", letter: "F", de: "das Feuer", en: "fire" },
  { level: "A1", letter: "F", de: "das Fieber", en: "fever" },
  { level: "A1", letter: "F", de: "der Film, -e", en: "film, movie" },
  { level: "A1", letter: "F", de: "finden", en: "to find" },
  { level: "A1", letter: "F", de: "die Firma", en: "company" },
  { level: "A1", letter: "F", de: "der Fisch, -e", en: "fish" },
  { level: "A1", letter: "F", de: "die Flasche, -n", en: "bottle" },
  { level: "A1", letter: "F", de: "das Fleisch", en: "meat" },
  { level: "A1", letter: "F", de: "fliegen", en: "to fly" },
  { level: "A1", letter: "A", de: "abfliegen", en: "to take off (plane)" },
  { level: "A1", letter: "A", de: "der Abflug", en: "departure (flight)" },
  { level: "A1", letter: "F", de: "der Flughafen", en: "airport" },
  { level: "A1", letter: "F", de: "das Flugzeug", en: "airplane" },
  { level: "A1", letter: "F", de: "das Formular, -e", en: "form" },
  { level: "A1", letter: "F", de: "das Foto, -s", en: "photo" },
  { level: "A1", letter: "F", de: "fragen", en: "to ask" },
  { level: "A1", letter: "F", de: "die Frage, -n", en: "question" },
  { level: "A1", letter: "F", de: "die Frau, -en", en: "woman, Mrs." },
  { level: "A1", letter: "F", de: "frei", en: "free, available" },
  { level: "A1", letter: "F", de: "die Freizeit", en: "free time" },
  { level: "A1", letter: "F", de: "fremd", en: "foreign, strange" },
  { level: "A1", letter: "F", de: "(sich) freuen", en: "to be happy, look forward to" },
  { level: "A1", letter: "F", de: "der Freund, -e", en: "friend" },
  { level: "A1", letter: "F", de: "früher", en: "earlier, in the past" },
  { level: "A1", letter: "F", de: "frühstücken", en: "to have breakfast" },
  { level: "A1", letter: "F", de: "das Frühstück", en: "breakfast" },
  { level: "A1", letter: "F", de: "die Führung", en: "guided tour" },
  { level: "A1", letter: "F", de: "für", en: "for" },
  { level: "A1", letter: "F", de: "der Fuß, -ü, e", en: "foot" },
  { level: "A1", letter: "F", de: "der Fußball", en: "soccer, football" },
  { level: "A1", letter: "G", de: "der Garten", en: "garden" },
  { level: "A1", letter: "G", de: "der Gast, -ä, e", en: "guest" },
  { level: "A1", letter: "G", de: "geben", en: "to give" },
  { level: "A1", letter: "G", de: "geboren", en: "born" },
  { level: "A1", letter: "G", de: "das Geburtsjahr", en: "year of birth" },
  { level: "A1", letter: "G", de: "der Geburtsort", en: "place of birth" },
  { level: "A1", letter: "G", de: "der Geburtstag", en: "birthday" },
  { level: "A1", letter: "G", de: "gefallen", en: "to please, like" },
  { level: "A1", letter: "G", de: "gegen", en: "against, around (time)" },
  { level: "A1", letter: "G", de: "gehen", en: "to go, walk" },
  { level: "A1", letter: "G", de: "gehören", en: "to belong" },
  { level: "A1", letter: "G", de: "das Geld", en: "money" },
  { level: "A1", letter: "G", de: "das Gemüse", en: "vegetables" },
  { level: "A1", letter: "G", de: "das Gepäck", en: "luggage" },
  { level: "A1", letter: "G", de: "gerade", en: "just, right now" },
  { level: "A1", letter: "G", de: "geradeaus", en: "straight ahead" },
  { level: "A1", letter: "G", de: "gern(e)", en: "gladly" },
  { level: "A1", letter: "G", de: "das Geschäft, -e", en: "shop, business" },
  { level: "A1", letter: "G", de: "das Geschenk, -e", en: "gift" },
  { level: "A1", letter: "G", de: "die Geschwister (pl.)", en: "siblings" },
  { level: "A1", letter: "G", de: "das Gespräch, -e", en: "conversation" },
  { level: "A1", letter: "G", de: "gestern", en: "yesterday" },
  { level: "A1", letter: "G", de: "gestorben", en: "died" },
  { level: "A1", letter: "G", de: "das Getränk, -e", en: "drink" },
  { level: "A1", letter: "G", de: "das Gewicht", en: "weight" },
  { level: "A1", letter: "G", de: "gewinnen", en: "to win" },
  { level: "A1", letter: "G", de: "das Glas, -ä, er", en: "glass" },
  { level: "A1", letter: "G", de: "glauben", en: "to believe" },
  { level: "A1", letter: "G", de: "gleich", en: "same; right away" },
  { level: "A1", letter: "G", de: "das Gleis, -e", en: "(train) track" },
  { level: "A1", letter: "G", de: "das Glück", en: "luck" },
  { level: "A1", letter: "G", de: "glücklich", en: "happy" },
  { level: "A1", letter: "G", de: "der Glückwunsch", en: "congratulations" },
  { level: "A1", letter: "G", de: "Grad (Celsius)", en: "degree(s)" },
  { level: "A1", letter: "G", de: "gratulieren", en: "to congratulate" },
  { level: "A1", letter: "G", de: "grillen", en: "to grill, barbecue" },
  { level: "A1", letter: "G", de: "groß", en: "big, tall" },
  { level: "A1", letter: "G", de: "die Größe", en: "size" },
  { level: "A1", letter: "G", de: "die Großeltern (pl.)", en: "grandparents" },
  { level: "A1", letter: "G", de: "die Großmutter", en: "grandmother" },
  { level: "A1", letter: "G", de: "der Großvater", en: "grandfather" },
  { level: "A1", letter: "G", de: "die Gruppe, -n", en: "group" },
  { level: "A1", letter: "G", de: "der Gruß, -ü, e", en: "greeting" },
  { level: "A1", letter: "G", de: "gültig", en: "valid" },
  { level: "A1", letter: "G", de: "günstig", en: "favorable, cheap" },
  { level: "A1", letter: "G", de: "gut", en: "good" },
  { level: "A1", letter: "H", de: "das Haar, -e", en: "hair" },
  { level: "A1", letter: "H", de: "haben", en: "to have" },
  { level: "A1", letter: "H", de: "das Hähnchen, -", en: "chicken" },
  { level: "A1", letter: "H", de: "die Halbpension", en: "half board" },
  { level: "A1", letter: "H", de: "die Halle", en: "hall" },
  { level: "A1", letter: "H", de: "hallo", en: "hello" },
  { level: "A1", letter: "H", de: "halten", en: "to stop, hold" },
  { level: "A1", letter: "H", de: "die Haltestelle", en: "(bus/tram) stop" },
  { level: "A1", letter: "H", de: "die Hand, -ä, e", en: "hand" },
  { level: "A1", letter: "H", de: "das Handy, -s", en: "mobile phone" },
  { level: "A1", letter: "H", de: "das Haus, -ä, er", en: "house" },
  { level: "A1", letter: "H", de: "die Hausaufgabe, -n", en: "homework" },
  { level: "A1", letter: "H", de: "die Hausfrau/der Hausmann", en: "housewife/househusband" },
  { level: "A1", letter: "H", de: "die Heimat", en: "homeland" },
  { level: "A1", letter: "H", de: "heiraten", en: "to marry" },
  { level: "A1", letter: "H", de: "heißen", en: "to be called" },
  { level: "A1", letter: "H", de: "helfen", en: "to help" },
  { level: "A1", letter: "H", de: "hell", en: "bright, light" },
  { level: "A1", letter: "H", de: "der Herd", en: "stove" },
  { level: "A1", letter: "H", de: "der Herr, -en", en: "man, Mr." },
  { level: "A1", letter: "H", de: "herzlich", en: "cordial, warm" },
  { level: "A1", letter: "H", de: "heute", en: "today" },
  { level: "A1", letter: "H", de: "hier", en: "here" },
  { level: "A1", letter: "H", de: "die Hilfe", en: "help" },
  { level: "A1", letter: "H", de: "hinten", en: "at the back" },
  { level: "A1", letter: "H", de: "das Hobby, -s", en: "hobby" },
  { level: "A1", letter: "H", de: "hoch", en: "high" },
  { level: "A1", letter: "H", de: "die Hochzeit", en: "wedding" },
  { level: "A1", letter: "H", de: "holen", en: "to fetch, get" },
  { level: "A1", letter: "H", de: "hören", en: "to hear, listen" },
  { level: "A1", letter: "H", de: "das Hotel, -s", en: "hotel" },
  { level: "A1", letter: "H", de: "der Hund, -e", en: "dog" },
  { level: "A1", letter: "H", de: "der Hunger", en: "hunger" },
  { level: "A1", letter: "I", de: "ich", en: "I" },
  { level: "A1", letter: "I", de: "ihr/ihm/ihn", en: "her/him (dative)/him (accusative)" },
  { level: "A1", letter: "I", de: "immer", en: "always" },
  { level: "A1", letter: "I", de: "in", en: "in" },
  { level: "A1", letter: "I", de: "die Information, -en", en: "information" },
  { level: "A1", letter: "I", de: "international", en: "international" },
  { level: "A1", letter: "I", de: "das Internet", en: "internet" },
  { level: "A1", letter: "J", de: "ja", en: "yes" },
  { level: "A1", letter: "J", de: "die Jacke, -n", en: "jacket" },
  { level: "A1", letter: "J", de: "jed-", en: "every, each" },
  { level: "A1", letter: "J", de: "jetzt", en: "now" },
  { level: "A1", letter: "J", de: "der Job, -s", en: "job" },
  { level: "A1", letter: "J", de: "der Jugendliche, -n", en: "young person, teenager" },
  { level: "A1", letter: "J", de: "jung", en: "young" },
  { level: "A1", letter: "J", de: "der Junge, -n", en: "boy" },
  { level: "A1", letter: "K", de: "der Kaffee", en: "coffee" },
  { level: "A1", letter: "K", de: "kaputt", en: "broken" },
  { level: "A1", letter: "K", de: "die Karte, -n", en: "card, menu, ticket" },
  { level: "A1", letter: "D", de: "die (Kredit)Karte, -n", en: "(credit) card" },
  { level: "A1", letter: "K", de: "die Kartoffel, -n", en: "potato" },
  { level: "A1", letter: "K", de: "die Kasse", en: "cash register, checkout" },
  { level: "A1", letter: "K", de: "kaufen", en: "to buy" },
  { level: "A1", letter: "K", de: "kein", en: "no, not any" },
  { level: "A1", letter: "K", de: "kennen", en: "to know (a person/thing)" },
  { level: "A1", letter: "K", de: "kennenlernen", en: "to get to know, meet" },
  { level: "A1", letter: "K", de: "das Kind, -er", en: "child" },
  { level: "A1", letter: "K", de: "der Kindergarten", en: "kindergarten" },
  { level: "A1", letter: "K", de: "das Kino, -s", en: "cinema" },
  { level: "A1", letter: "K", de: "der Kiosk", en: "kiosk" },
  { level: "A1", letter: "K", de: "klar", en: "clear, sure" },
  { level: "A1", letter: "K", de: "die Klasse", en: "class" },
  { level: "A1", letter: "K", de: "die Kleidung", en: "clothing" },
  { level: "A1", letter: "K", de: "klein", en: "small" },
  { level: "A1", letter: "K", de: "kochen", en: "to cook" },
  { level: "A1", letter: "K", de: "der Koffer, -", en: "suitcase" },
  { level: "A1", letter: "K", de: "der Kollege, -n", en: "colleague" },
  { level: "A1", letter: "K", de: "kommen", en: "to come" },
  { level: "A1", letter: "K", de: "können", en: "can, to be able to" },
  { level: "A1", letter: "K", de: "das Konto", en: "account (bank)" },
  { level: "A1", letter: "K", de: "der Kopf", en: "head" },
  { level: "A1", letter: "K", de: "kosten", en: "to cost" },
  { level: "A1", letter: "K", de: "krank", en: "sick" },
  { level: "A1", letter: "K", de: "kriegen", en: "to get, receive" },
  { level: "A1", letter: "K", de: "die Küche", en: "kitchen" },
  { level: "A1", letter: "K", de: "der Kuchen", en: "cake" },
  { level: "A1", letter: "K", de: "der Kugelschreiber", en: "ballpoint pen" },
  { level: "A1", letter: "K", de: "der Kühlschrank", en: "refrigerator" },
  { level: "A1", letter: "K", de: "kulturell", en: "cultural" },
  { level: "A1", letter: "S", de: "sich kümmern", en: "to take care of" },
  { level: "A1", letter: "K", de: "der Kunde, -n", en: "customer" },
  { level: "A1", letter: "K", de: "der Kurs, -e", en: "course" },
  { level: "A1", letter: "K", de: "kurz", en: "short" },
  { level: "A1", letter: "L", de: "lachen", en: "to laugh" },
  { level: "A1", letter: "L", de: "der Laden, -ä", en: "shop, store" },
  { level: "A1", letter: "L", de: "das Land, -ä, er", en: "country" },
  { level: "A1", letter: "L", de: "lang", en: "long" },
  { level: "A1", letter: "L", de: "lange", en: "for a long time" },
  { level: "A1", letter: "L", de: "langsam", en: "slow" },
  { level: "A1", letter: "L", de: "laufen", en: "to run, walk" },
  { level: "A1", letter: "L", de: "laut", en: "loud" },
  { level: "A1", letter: "L", de: "leben", en: "to live" },
  { level: "A1", letter: "L", de: "das Leben", en: "life" },
  { level: "A1", letter: "L", de: "die Lebensmittel (pl.)", en: "groceries, food" },
  { level: "A1", letter: "L", de: "ledig", en: "single (unmarried)" },
  { level: "A1", letter: "L", de: "legen", en: "to lay, put" },
  { level: "A1", letter: "L", de: "der Lehrer, -", en: "teacher" },
  { level: "A1", letter: "L", de: "leicht", en: "light, easy" },
  { level: "A1", letter: "L", de: "leider", en: "unfortunately" },
  { level: "A1", letter: "L", de: "leise", en: "quiet" },
  { level: "A1", letter: "L", de: "lernen", en: "to learn" },
  { level: "A1", letter: "L", de: "lesen", en: "to read" },
  { level: "A1", letter: "L", de: "letzt-", en: "last" },
  { level: "A1", letter: "L", de: "die Leute (pl.)", en: "people" },
  { level: "A1", letter: "L", de: "das Licht", en: "light" },
  { level: "A1", letter: "L", de: "lieb-", en: "dear" },
  { level: "A1", letter: "L", de: "lieben", en: "to love" },
  { level: "A1", letter: "L", de: "lieber", en: "preferably, rather" },
  { level: "A1", letter: "L", de: "Lieblings-", en: "favorite" },
  { level: "A1", letter: "L", de: "das Lied, -er", en: "song" },
  { level: "A1", letter: "L", de: "liegen", en: "to lie, be located" },
  { level: "A1", letter: "L", de: "links", en: "left" },
  { level: "A1", letter: "L", de: "der Lkw, -s", en: "truck" },
  { level: "A1", letter: "L", de: "das Lokal", en: "pub, restaurant" },
  { level: "A1", letter: "L", de: "die Lösung, -en", en: "solution" },
  { level: "A1", letter: "L", de: "lustig", en: "funny" },
  { level: "A1", letter: "M", de: "machen", en: "to make, do" },
  { level: "A1", letter: "M", de: "das Mädchen, -", en: "girl" },
  { level: "A1", letter: "M", de: "man", en: "one, you (impersonal)" },
  { level: "A1", letter: "M", de: "der Mann, -ä, er", en: "man, husband" },
  { level: "A1", letter: "M", de: "männlich", en: "male" },
  { level: "A1", letter: "M", de: "die Maschine, -n", en: "machine" },
  { level: "A1", letter: "M", de: "das Meer", en: "sea" },
  { level: "A1", letter: "M", de: "mehr", en: "more" },
  { level: "A1", letter: "M", de: "mein", en: "my" },
  { level: "A1", letter: "M", de: "meist-", en: "most" },
  { level: "A1", letter: "M", de: "der Mensch, -en", en: "person, human" },
  { level: "A1", letter: "M", de: "mieten", en: "to rent" },
  { level: "A1", letter: "M", de: "die Miete", en: "rent" },
  { level: "A1", letter: "M", de: "die Milch", en: "milk" },
  { level: "A1", letter: "M", de: "mit", en: "with" },
  { level: "A1", letter: "M", de: "mitbringen", en: "to bring along" },
  { level: "A1", letter: "M", de: "mitkommen", en: "to come along" },
  { level: "A1", letter: "M", de: "mitmachen", en: "to join in, participate" },
  { level: "A1", letter: "M", de: "mitnehmen", en: "to take along" },
  { level: "A1", letter: "M", de: "die Mitte", en: "middle" },
  { level: "A1", letter: "M", de: "die Möbel (pl.)", en: "furniture" },
  { level: "A1", letter: "M", de: "möchten", en: "would like" },
  { level: "A1", letter: "M", de: "mögen", en: "to like" },
  { level: "A1", letter: "M", de: "möglich", en: "possible" },
  { level: "A1", letter: "M", de: "der Moment", en: "moment" },
  { level: "A1", letter: "M", de: "morgen", en: "tomorrow" },
  { level: "A1", letter: "M", de: "müde", en: "tired" },
  { level: "A1", letter: "M", de: "der Mund", en: "mouth" },
  { level: "A1", letter: "M", de: "müssen", en: "must, to have to" },
  { level: "A1", letter: "M", de: "die Mutter, -ü", en: "mother" },
  { level: "A1", letter: "N", de: "nach", en: "after, to (a place)" },
  { level: "A1", letter: "N", de: "nächst-", en: "next" },
  { level: "A1", letter: "N", de: "der Name, -n", en: "name" },
  { level: "A1", letter: "N", de: "nehmen", en: "to take" },
  { level: "A1", letter: "N", de: "nein", en: "no" },
  { level: "A1", letter: "N", de: "neu", en: "new" },
  { level: "A1", letter: "N", de: "nicht", en: "not" },
  { level: "A1", letter: "N", de: "nichts", en: "nothing" },
  { level: "A1", letter: "N", de: "nie", en: "never" },
  { level: "A1", letter: "N", de: "noch", en: "still, yet" },
  { level: "A1", letter: "N", de: "normal", en: "normal" },
  { level: "A1", letter: "N", de: "die Nummer, -n", en: "number" },
  { level: "A1", letter: "N", de: "nur", en: "only" },
  { level: "A1", letter: "O", de: "oben", en: "above, upstairs" },
  { level: "A1", letter: "O", de: "das Obst", en: "fruit" },
  { level: "A1", letter: "O", de: "oder", en: "or" },
  { level: "A1", letter: "O", de: "öffnen", en: "to open" },
  { level: "A1", letter: "G", de: "geöffnet", en: "open" },
  { level: "A1", letter: "O", de: "oft", en: "often" },
  { level: "A1", letter: "O", de: "ohne", en: "without" },
  { level: "A1", letter: "O", de: "das Öl", en: "oil" },
  { level: "A1", letter: "O", de: "die Oma, -s", en: "grandma" },
  { level: "A1", letter: "O", de: "der Opa, -s", en: "grandpa" },
  { level: "A1", letter: "O", de: "die Ordnung", en: "order" },
  { level: "A1", letter: "O", de: "der Ort, -e", en: "place" },
  { level: "A1", letter: "P", de: "das Papier", en: "paper" },
  { level: "A1", letter: "P", de: "die Papiere (pl.)", en: "documents, papers" },
  { level: "A1", letter: "P", de: "der Partner, -/die Partnerin, -nen", en: "partner" },
  { level: "A1", letter: "P", de: "die Party", en: "party" },
  { level: "A1", letter: "P", de: "der Pass, -ä, e", en: "passport" },
  { level: "A1", letter: "P", de: "die Pause, -n", en: "break, pause" },
  { level: "A1", letter: "P", de: "der Plan, -ä, e", en: "plan, map" },
  { level: "A1", letter: "P", de: "der Platz, -ä, e", en: "seat, place, square" },
  { level: "A1", letter: "P", de: "die Polizei", en: "police" },
  { level: "A1", letter: "P", de: "die Pommes frites (pl.)", en: "fries" },
  { level: "A1", letter: "P", de: "die Post", en: "post office, mail" },
  { level: "A1", letter: "P", de: "die Postleitzahl", en: "postal code" },
  { level: "A1", letter: "P", de: "das Praktikum", en: "internship" },
  { level: "A1", letter: "P", de: "die Praxis", en: "(doctor's) practice" },
  { level: "A1", letter: "P", de: "der Preis, -e", en: "price" },
  { level: "A1", letter: "P", de: "das Problem, -e", en: "problem" },
  { level: "A1", letter: "P", de: "der Prospekt, -e", en: "brochure" },
  { level: "A1", letter: "P", de: "die Prüfung", en: "exam" },
  { level: "A1", letter: "P", de: "pünktlich", en: "punctual" },
  { level: "A1", letter: "R", de: "Rad fahren", en: "to cycle" },
  { level: "A1", letter: "R", de: "rauchen", en: "to smoke" },
  { level: "A1", letter: "R", de: "der Raum, -ä, e", en: "room, space" },
  { level: "A1", letter: "R", de: "die Rechnung, -en", en: "bill, invoice" },
  { level: "A1", letter: "R", de: "rechts", en: "right (direction)" },
  { level: "A1", letter: "R", de: "regnen", en: "to rain" },
  { level: "A1", letter: "R", de: "der Regen", en: "rain" },
  { level: "A1", letter: "R", de: "der Reis", en: "rice" },
  { level: "A1", letter: "R", de: "reisen", en: "to travel" },
  { level: "A1", letter: "R", de: "die Reise", en: "trip, journey" },
  { level: "A1", letter: "R", de: "das Reisebüro, -s", en: "travel agency" },
  { level: "A1", letter: "R", de: "der Reiseführer", en: "travel guide/guidebook" },
  { level: "A1", letter: "R", de: "reparieren", en: "to repair" },
  { level: "A1", letter: "R", de: "die Reparatur", en: "repair" },
  { level: "A1", letter: "R", de: "das Restaurant, -s", en: "restaurant" },
  { level: "A1", letter: "R", de: "die Rezeption", en: "reception" },
  { level: "A1", letter: "R", de: "richtig", en: "correct" },
  { level: "A1", letter: "R", de: "riechen", en: "to smell" },
  { level: "A1", letter: "R", de: "ruhig", en: "quiet, calm" },
  { level: "A1", letter: "S", de: "der Saft", en: "juice" },
  { level: "A1", letter: "S", de: "sagen", en: "to say" },
  { level: "A1", letter: "S", de: "der Salat", en: "salad" },
  { level: "A1", letter: "S", de: "das Salz", en: "salt" },
  { level: "A1", letter: "S", de: "der Satz, -ä, e", en: "sentence" },
  { level: "A1", letter: "S", de: "die S-Bahn", en: "urban railway" },
  { level: "A1", letter: "S", de: "der Schalter", en: "counter, window (service)" },
  { level: "A1", letter: "S", de: "scheinen", en: "to shine; to seem" },
  { level: "A1", letter: "S", de: "schicken", en: "to send" },
  { level: "A1", letter: "S", de: "das Schild, -er", en: "sign" },
  { level: "A1", letter: "S", de: "der Schinken, -", en: "ham" },
  { level: "A1", letter: "S", de: "schlafen", en: "to sleep" },
  { level: "A1", letter: "S", de: "schlecht", en: "bad" },
  { level: "A1", letter: "S", de: "schließen", en: "to close" },
  { level: "A1", letter: "G", de: "geschlossen", en: "closed" },
  { level: "A1", letter: "S", de: "der Schluss", en: "end" },
  { level: "A1", letter: "S", de: "der Schlüssel, -", en: "key" },
  { level: "A1", letter: "S", de: "schmecken", en: "to taste" },
  { level: "A1", letter: "S", de: "schnell", en: "fast" },
  { level: "A1", letter: "S", de: "schon", en: "already" },
  { level: "A1", letter: "S", de: "schön", en: "beautiful, nice" },
  { level: "A1", letter: "S", de: "der Schrank, -ä, e", en: "cupboard, closet" },
  { level: "A1", letter: "S", de: "schreiben", en: "to write" },
  { level: "A1", letter: "S", de: "der Schuh, -e", en: "shoe" },
  { level: "A1", letter: "S", de: "die Schule", en: "school" },
  { level: "A1", letter: "S", de: "der Schüler, -", en: "pupil, student" },
  { level: "A1", letter: "S", de: "schwer", en: "heavy, difficult" },
  { level: "A1", letter: "S", de: "die Schwester, -n", en: "sister" },
  { level: "A1", letter: "S", de: "schwimmen", en: "to swim" },
  { level: "A1", letter: "S", de: "das Schwimmbad", en: "swimming pool" },
  { level: "A1", letter: "S", de: "der See", en: "lake" },
  { level: "A1", letter: "S", de: "sehen", en: "to see" },
  { level: "A1", letter: "S", de: "die Sehenswürdigkeit, -en", en: "sight, attraction" },
  { level: "A1", letter: "S", de: "sehr", en: "very" },
  { level: "A1", letter: "S", de: "sein", en: "to be" },
  { level: "A1", letter: "A", de: "an sein", en: "to be on (device)" },
  { level: "A1", letter: "A", de: "auf sein", en: "to be open" },
  { level: "A1", letter: "W", de: "weg sein", en: "to be gone" },
  { level: "A1", letter: "Z", de: "zu sein", en: "to be closed" },
  { level: "A1", letter: "S", de: "seit", en: "since" },
  { level: "A1", letter: "S", de: "selbstständig", en: "self-employed, independent" },
  { level: "A1", letter: "S", de: "sich", en: "oneself" },
  { level: "A1", letter: "S", de: "sie", en: "she, they" },
  { level: "A1", letter: "S", de: "Sie", en: "you (formal)" },
  { level: "A1", letter: "S", de: "sitzen", en: "to sit" },
  { level: "A1", letter: "S", de: "so", en: "so, like this" },
  { level: "A1", letter: "S", de: "das Sofa", en: "sofa" },
  { level: "A1", letter: "S", de: "sofort", en: "immediately" },
  { level: "A1", letter: "S", de: "der Sohn, -ö, e", en: "son" },
  { level: "A1", letter: "S", de: "sollen", en: "should" },
  { level: "A1", letter: "S", de: "die Sonne", en: "sun" },
  { level: "A1", letter: "S", de: "spät", en: "late" },
  { level: "A1", letter: "S", de: "später", en: "later" },
  { level: "A1", letter: "S", de: "die Speisekarte", en: "menu" },
  { level: "A1", letter: "S", de: "spielen", en: "to play" },
  { level: "A1", letter: "S", de: "der Sport", en: "sport" },
  { level: "A1", letter: "S", de: "die Sprache, -n", en: "language" },
  { level: "A1", letter: "S", de: "sprechen", en: "to speak" },
  { level: "A1", letter: "S", de: "die Stadt, -ä, e", en: "city" },
  { level: "A1", letter: "S", de: "stehen", en: "to stand" },
  { level: "A1", letter: "S", de: "die Stelle, -n", en: "position, job" },
  { level: "A1", letter: "S", de: "stellen", en: "to put, place" },
  { level: "A1", letter: "S", de: "der Stock", en: "floor (of a building)" },
  { level: "A1", letter: "S", de: "die Straße, -n", en: "street" },
  { level: "A1", letter: "S", de: "die Straßenbahn", en: "tram" },
  { level: "A1", letter: "S", de: "studieren", en: "to study (university)" },
  { level: "A1", letter: "S", de: "das Studium", en: "studies (university)" },
  { level: "A1", letter: "S", de: "der Student, -en", en: "student" },
  { level: "A1", letter: "S", de: "die Stunde, -n", en: "hour" },
  { level: "A1", letter: "S", de: "suchen", en: "to look for" },
  { level: "A1", letter: "T", de: "tanzen", en: "to dance" },
  { level: "A1", letter: "T", de: "die Tasche, -n", en: "bag" },
  { level: "A1", letter: "T", de: "das Taxi, -s", en: "taxi" },
  { level: "A1", letter: "T", de: "der Tee", en: "tea" },
  { level: "A1", letter: "T", de: "der Teil, -e", en: "part" },
  { level: "A1", letter: "T", de: "telefonieren", en: "to phone" },
  { level: "A1", letter: "T", de: "das Telefon", en: "telephone" },
  { level: "A1", letter: "T", de: "der Termin, -e", en: "appointment" },
  { level: "A1", letter: "T", de: "der Test", en: "test" },
  { level: "A1", letter: "T", de: "teuer", en: "expensive" },
  { level: "A1", letter: "T", de: "der Text, -e", en: "text" },
  { level: "A1", letter: "T", de: "das Thema", en: "topic" },
  { level: "A1", letter: "T", de: "das Ticket, -s", en: "ticket" },
  { level: "A1", letter: "T", de: "der Tisch, -e", en: "table" },
  { level: "A1", letter: "T", de: "die Tochter, -ö", en: "daughter" },
  { level: "A1", letter: "T", de: "die Toilette, -en", en: "toilet" },
  { level: "A1", letter: "T", de: "die Tomate, -n", en: "tomato" },
  { level: "A1", letter: "T", de: "tot", en: "dead" },
  { level: "A1", letter: "T", de: "(sich) treffen", en: "to meet" },
  { level: "A1", letter: "T", de: "die Treppe, -n", en: "stairs" },
  { level: "A1", letter: "T", de: "trinken", en: "to drink" },
  { level: "A1", letter: "T", de: "tschüss", en: "bye" },
  { level: "A1", letter: "T", de: "tun", en: "to do" },
  { level: "A1", letter: "U", de: "über", en: "over, above, about" },
  { level: "A1", letter: "U", de: "übernachten", en: "to stay overnight" },
  { level: "A1", letter: "U", de: "überweisen", en: "to transfer (money)" },
  { level: "A1", letter: "U", de: "die Uhr", en: "clock, o'clock" },
  { level: "A1", letter: "U", de: "um", en: "at (time); around" },
  { level: "A1", letter: "U", de: "umziehen", en: "to move (house)" },
  { level: "A1", letter: "U", de: "und", en: "and" },
  { level: "A1", letter: "U", de: "unser-", en: "our" },
  { level: "A1", letter: "U", de: "unten", en: "below, downstairs" },
  { level: "A1", letter: "U", de: "unter", en: "under, below" },
  { level: "A1", letter: "U", de: "der Unterricht", en: "lesson, class" },
  { level: "A1", letter: "U", de: "unterschreiben", en: "to sign" },
  { level: "A1", letter: "U", de: "die Unterschrift", en: "signature" },
  { level: "A1", letter: "U", de: "der Urlaub", en: "vacation" },
  { level: "A1", letter: "V", de: "der Vater, -ä", en: "father" },
  { level: "A1", letter: "V", de: "verboten", en: "forbidden" },
  { level: "A1", letter: "V", de: "verdienen", en: "to earn" },
  { level: "A1", letter: "V", de: "der Verein", en: "club, association" },
  { level: "A1", letter: "V", de: "verheiratet", en: "married" },
  { level: "A1", letter: "V", de: "verkaufen", en: "to sell" },
  { level: "A1", letter: "V", de: "der Verkäufer, -", en: "salesperson" },
  { level: "A1", letter: "V", de: "vermieten", en: "to rent out" },
  { level: "A1", letter: "V", de: "der Vermieter", en: "landlord" },
  { level: "A1", letter: "V", de: "verstehen", en: "to understand" },
  { level: "A1", letter: "V", de: "der Verwandte, -n", en: "relative" },
  { level: "A1", letter: "V", de: "viel", en: "much, a lot" },
  { level: "A1", letter: "V", de: "vielleicht", en: "maybe" },
  { level: "A1", letter: "V", de: "von", en: "from, of" },
  { level: "A1", letter: "V", de: "vor", en: "before, in front of" },
  { level: "A1", letter: "V", de: "der Vorname, -n", en: "first name" },
  { level: "A1", letter: "V", de: "die Vorsicht", en: "caution" },
  { level: "A1", letter: "V", de: "(sich) vorstellen", en: "to introduce (oneself)" },
  { level: "A1", letter: "V", de: "die Vorwahl", en: "area code" },
  { level: "A1", letter: "W", de: "wandern", en: "to hike" },
  { level: "A1", letter: "W", de: "wann", en: "when" },
  { level: "A1", letter: "W", de: "warten", en: "to wait" },
  { level: "A1", letter: "W", de: "warum", en: "why" },
  { level: "A1", letter: "W", de: "was", en: "what" },
  { level: "A1", letter: "W", de: "was für ein", en: "what kind of" },
  { level: "A1", letter: "W", de: "(sich) waschen", en: "to wash (oneself)" },
  { level: "A1", letter: "W", de: "das Wasser", en: "water" },
  { level: "A1", letter: "W", de: "weh tun", en: "to hurt" },
  { level: "A1", letter: "W", de: "weiblich", en: "female" },
  { level: "A1", letter: "W", de: "der Wein", en: "wine" },
  { level: "A1", letter: "W", de: "weit", en: "far" },
  { level: "A1", letter: "W", de: "weiter", en: "further" },
  { level: "A1", letter: "W", de: "welch-", en: "which" },
  { level: "A1", letter: "W", de: "die Welt", en: "world" },
  { level: "A1", letter: "W", de: "wenig", en: "little, few" },
  { level: "A1", letter: "W", de: "wer", en: "who" },
  { level: "A1", letter: "W", de: "werden", en: "to become" },
  { level: "A1", letter: "W", de: "das Wetter", en: "weather" },
  { level: "A1", letter: "W", de: "wichtig", en: "important" },
  { level: "A1", letter: "W", de: "wie", en: "how, as" },
  { level: "A1", letter: "W", de: "wiederholen", en: "to repeat" },
  { level: "A1", letter: "W", de: "das Wiederhören", en: "goodbye (on phone)" },
  { level: "A1", letter: "W", de: "das Wiedersehen", en: "goodbye" },
  { level: "A1", letter: "W", de: "wie viel", en: "how much" },
  { level: "A1", letter: "W", de: "willkommen", en: "welcome" },
  { level: "A1", letter: "W", de: "der Wind", en: "wind" },
  { level: "A1", letter: "W", de: "wir", en: "we" },
  { level: "A1", letter: "W", de: "wissen", en: "to know (a fact)" },
  { level: "A1", letter: "W", de: "wo", en: "where" },
  { level: "A1", letter: "W", de: "woher", en: "where from" },
  { level: "A1", letter: "W", de: "wohin", en: "where to" },
  { level: "A1", letter: "W", de: "wohnen", en: "to live, reside" },
  { level: "A1", letter: "W", de: "die Wohnung, -en", en: "apartment" },
  { level: "A1", letter: "W", de: "wollen", en: "to want" },
  { level: "A1", letter: "W", de: "das Wort, -ö, er/-e", en: "word" },
  { level: "A1", letter: "W", de: "wunderbar", en: "wonderful" },
  { level: "A1", letter: "Z", de: "zahlen", en: "to pay" },
  { level: "A1", letter: "Z", de: "die Zeit", en: "time" },
  { level: "A1", letter: "Z", de: "zurzeit", en: "currently" },
  { level: "A1", letter: "Z", de: "die Zeitung, -en", en: "newspaper" },
  { level: "A1", letter: "Z", de: "die Zigarette, -n", en: "cigarette" },
  { level: "A1", letter: "Z", de: "das Zimmer, -", en: "room" },
  { level: "A1", letter: "Z", de: "der Zoll", en: "customs" },
  { level: "A1", letter: "Z", de: "zu", en: "to, closed, too" },
  { level: "A1", letter: "Z", de: "zufrieden", en: "satisfied" },
  { level: "A1", letter: "Z", de: "der Zug, -ü, e", en: "train" },
  { level: "A1", letter: "Z", de: "zurück", en: "back" },
  { level: "A1", letter: "Z", de: "zusammen", en: "together" },
  { level: "A1", letter: "Z", de: "zwischen", en: "between" },
];

function getWordsByLevel(level) {
  return WORDS.filter(w => w.level === level);
}

function wordCount(level) {
  return getWordsByLevel(level).length;
}

/** Group a list of word entries into { letter, words }[] buckets, A–Z. */
function groupWordsByLetter(words) {
  const byLetter = {};
  words.forEach(w => {
    if (!byLetter[w.letter]) byLetter[w.letter] = [];
    byLetter[w.letter].push(w);
  });
  return Object.keys(byLetter)
    .sort()
    .map(letter => ({ letter, words: byLetter[letter] }));
}

/** Filter words for a level by a free-text query against German or English. */
function searchWords(level, query) {
  const words = getWordsByLevel(level);
  const q = query.trim().toLowerCase();
  if (!q) return words;
  return words.filter(w =>
    w.de.toLowerCase().includes(q) || w.en.toLowerCase().includes(q)
  );
}

/** A small, friendly sample of A1 words for the homepage teaser. */
const FEATURED_WORD_KEYS = ["hallo", "danke", "bitte", "tschüss", "das Wasser", "der Kaffee"];

function getFeaturedWords() {
  return FEATURED_WORD_KEYS
    .map(key => WORDS.find(w => w.de === key))
    .filter(Boolean);
}
